image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install uv
      uv sync
    command: |
      echo "🚀 Gitpod workspace ready!"
      echo "Python version: $(python --version)"
      echo "Available Jupyter kernels:"
      jupyter kernelspec list
      echo ""
      echo "To start Jupyter Lab: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"

ports:
  - port: 8888
    onOpen: open-browser
    description: Jupyter Lab
  - port: 8000
    onOpen: notify
    description: Development Server
  - port: 3000
    onOpen: notify
    description: Frontend Server

vscode:
  extensions:
    - ms-python.python
    - ms-python.flake8
    - ms-python.black-formatter
    - ms-toolsai.jupyter
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - GitHub.copilot
    - GitHub.copilot-chat
    - ms-python.pylint
    - ms-python.autopep8

workspaceLocation: "."

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false