[project]
name = "jh-laboratory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "openai>=1.107.2",
    "requests>=2.32.5",
    "sa",
]

[tool.uv.sources]
sa = { path = "../jh-sa" }
